export type Series={id:string;name:string;description:string;created_at:string;counts?:Record<string,number>};
export type Fact={id:string;kind:string;entity:string;attribute:string;value:string;version:number;is_current:boolean;confidence:number};
export type Citation={chapter:string;section:string|null;page:number|null;chunk_id:string;evidence_text:string};
export type Finding={id:string;type:string;entity:string;attribute:string;existing_value:string|null;new_value:string;existing_evidence:Citation|null;new_evidence:Citation|null;explanation:string;confidence:number;severity:string;status:string};
export type ChatMessage={id:string;role:'user'|'assistant';content:string;citations:Citation[];grounded:boolean;created_at:string};
export type User={id:string;email:string;name:string;avatar_url:string|null};
const base=import.meta.env.VITE_API_URL??'';
export class ApiError extends Error{constructor(public status:number,message:string){super(message)}}
async function request<T>(path:string,init?:RequestInit):Promise<T>{const token=localStorage.getItem('continuum_session_token');const response=await fetch(`${base}${path}`,{...init,headers:{...(!(init?.body instanceof FormData)?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{}) ,...init?.headers}});if(!response.ok){const body=await response.json().catch(()=>({detail:'Request failed'}));throw new ApiError(response.status,body.detail??body.error?.message??'Request failed');}return response.json() as Promise<T>}
export const api={googleSignIn:(credential:string)=>request<{token:string;user:User}>('/api/v1/auth/google',{method:'POST',body:JSON.stringify({credential})}),series:()=>request<Series[]>('/api/v1/series'),seriesById:(id:string)=>request<Series>(`/api/v1/series/${id}`),createSeries:(name:string,description:string)=>request<Series>('/api/v1/series',{method:'POST',body:JSON.stringify({name,description})}),bible:(id:string)=>request<Fact[]>(`/api/v1/series/${id}/bible`),findings:(id:string)=>request<Finding[]>(`/api/v1/series/${id}/findings`),resolve:(id:string,resolution:string)=>request(`/api/v1/findings/${id}/approve`,{method:'POST',body:JSON.stringify({actor:'user',resolution,rationale:''})}),reject:(id:string)=>request(`/api/v1/findings/${id}/reject`,{method:'POST',body:JSON.stringify({actor:'user'})}),intentional:(id:string)=>request(`/api/v1/findings/${id}/intentional-change`,{method:'POST',body:JSON.stringify({actor:'user'})}),upload:(id:string,file:File)=>{const body=new FormData();body.append('file',file);body.append('actor','user');return request(`/api/v1/series/${id}/documents`,{method:'POST',body})},chat:(seriesId:string)=>request<{session_id:string|null;messages:ChatMessage[]}>(`/api/v1/series/${seriesId}/chat`),ask:(seriesId:string,question:string)=>request<{answer:string;citations:Citation[];grounded:boolean}>(`/api/v1/series/${seriesId}/chat`,{method:'POST',body:JSON.stringify({question})})};
