export type Series = {id:string;name:string;description:string;created_at:string;counts?:Record<string,number>};
export type Fact = {id:string;kind:string;entity:string;attribute:string;value:string;version:number;is_current:boolean;confidence:number};
export type Citation = {chapter:string;section:string|null;page:number|null;chunk_id:string;evidence_text:string};
export type Finding = {id:string;type:string;entity:string;attribute:string;existing_value:string|null;new_value:string;existing_evidence:Citation|null;new_evidence:Citation|null;explanation:string;confidence:number;severity:string;status:string};
export type RunError = {stage:string;message:string};
export type UploadResult = {id:string;filename:string;status:string;session_id:string;run_id:string;run_status:string;run_errors:RunError[]};
export type RunResult = {id:string;series_id:string;status:string;current_stage:string;completed_stages:string[];errors:RunError[]};
const base = import.meta.env.VITE_API_URL ?? '';
export class ApiError extends Error { constructor(public status:number,message:string){super(message)} }
async function request<T>(path:string, init?:RequestInit):Promise<T>{const token=localStorage.getItem('continuum_api_token');const response=await fetch(`${base}${path}`,{...init,headers:{...(!(init?.body instanceof FormData)?{'Content-Type':'application/json'}:{}),...(token?{'Authorization':`Bearer ${token}`}:{}) ,...init?.headers}});if(!response.ok){const body=await response.json().catch(()=>({detail:'Request failed'}));throw new ApiError(response.status,body.detail??body.error?.message??'Request failed');}return response.json() as Promise<T>}
export const api={series:()=>request<Series[]>('/api/v1/series'),seriesById:(id:string)=>request<Series>(`/api/v1/series/${id}`),createSeries:(name:string,description:string)=>request<Series>('/api/v1/series',{method:'POST',body:JSON.stringify({name,description})}),bible:(id:string)=>request<Fact[]>(`/api/v1/series/${id}/bible`),findings:(id:string)=>request<Finding[]>(`/api/v1/series/${id}/findings`),resolve:(id:string,resolution:string)=>request(`/api/v1/findings/${id}/approve`,{method:'POST',body:JSON.stringify({actor:'user',resolution,rationale:''})}),reject:(id:string)=>request(`/api/v1/findings/${id}/reject`,{method:'POST',body:JSON.stringify({actor:'user'})}),intentional:(id:string)=>request(`/api/v1/findings/${id}/intentional-change`,{method:'POST',body:JSON.stringify({actor:'user'})}),upload:(id:string,file:File)=>{const body=new FormData();body.append('file',file);body.append('actor','user');return request<UploadResult>(`/api/v1/series/${id}/documents`,{method:'POST',body})},run:(id:string)=>request(`/api/v1/series/${id}/runs`,{method:'POST',body:JSON.stringify({document_ids:[]})}),runById:(id:string)=>request<Record<string,unknown>>(`/api/v1/runs/${id}`),retryRun:(runId:string)=>request<RunResult>(`/api/v1/runs/${runId}/retry`,{method:'POST'})};
